variables:
  BRANCH_TESTING: "devel"
  BRANCH_STABLE: "0.1"


stages:
  - build
  - push_image

build_sandbox:
  stage: build
  only:
    - master
  script:
    - sudo docker build --no-cache -t noia/agent:sandbox .

build_devel:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_TESTING
  script:
    - sudo docker build --no-cache -t noia/agent:$CI_COMMIT_SHORT_SHA .

build_prod:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_STABLE
  when: manual
  script:
    - sudo docker build --no-cache -t noia/agent:$BRANCH_STABLE .

push_image_sandbox:
  stage: push_image
  only:
    - master
  script:
    - sudo docker push noia/agent:sandbox

push_image_devel:
  stage: push_image
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_TESTING
  script:
    - sudo docker push noia/agent:$CI_COMMIT_SHORT_SHA .

push_image_prod:
  stage: push_image
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $BRANCH_STABLE
  when: manual
  script:
    - sudo docker push noia/agent:$BRANCH_STABLE .