variables:
  PROD: "0.1"
  TEST: "devel"

stages:
  - build
  - push_image

build_sandbox:
  stage: build
  only:
    - master
  script:
    - sudo docker build --no-cache -t noia/agent:sandbox .

build_devel:
  stage: build
  only:
    - $TEST
  script:
    - sudo docker build --no-cache -t noia/agent:$TEST .

build_prod:
  stage: build
  only:
    - $PROD
  when: manual
  script:
    - sudo docker build --no-cache -t noia/agent:$PROD .

push_image_sandbox:
  stage: push_image
  only:
    - master
  script:
    - sudo docker push noia/agent:sandbox

push_image_devel:
  stage: push_image
  only:
    - $TEST
  script:
    - sudo docker push noia/agent:$TEST

push_image_prod:
  stage: push_image
  only:
    - $PROD
  when: manual
  script:
    - sudo docker push noia/agent:$PROD