variables:
  BRANCH_STABLE: "0.1"

.rules-def:
  rules:
    - if: &is-for-sandbox '$CI_COMMIT_BRANCH == "master"'
    - if: &is-for-prod '$CI_COMMIT_BRANCH == $BRANCH_STABLE'
    - if: &is-for-devel '$CI_COMMIT_TAG =~ /-(?:beta|rc)\d+$/'

stages:
  - build
  - push_image
  - prep_env
  - pypi

build_sandbox:
  stage: build
  rules:
    - if: *is-for-sandbox
  script:
    - sudo docker build --no-cache -t noia/agent:sandbox-$CI_COMMIT_SHORT_SHA -t noia/agent:sandbox -t noia/agent:latest .

build_devel:
  stage: build
  rules:
    - if: *is-for-devel
  script:
    - sudo docker build --no-cache -t noia/agent:$CI_COMMIT_TAG .

build_prod:
  stage: build
  rules:
    - if: *is-for-prod
  script:
    - sudo docker build --no-cache -t noia/agent:$BRANCH_STABLE .

push_image_sandbox:
  stage: push_image
  rules:
    - if: *is-for-sandbox
  script:
    - sudo docker push noia/agent:sandbox-$CI_COMMIT_SHORT_SHA
    - sudo docker push noia/agent:sandbox
    - sudo docker push noia/agent:latest

push_image_devel:
  stage: push_image
  rules:
    - if: *is-for-devel
  script:
    - sudo docker push noia/agent:$CI_COMMIT_TAG

push_image_prod:
  stage: push_image
  rules:
    - if: *is-for-prod
  script:
    - sudo docker push noia/agent:$BRANCH_STABLE

prepare_environment:
  stage: prep_env
  rules:
    - if: *is-for-sandbox
  script:
    - python3 --version
    - virtualenv-3 -p python3 build_env --no-pip
    - source build_env/bin/activate
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py "pip"==19.2.2
    - rm -rf get-pip.py
    - pip -V
    - deactivate

pypi:
  stage: pypi
  rules:
    - if: *is-for-sandbox
  script:
    - source build_env/bin/activate
    - pip install twine
    - python3 setup.py bdist_wheel
    - TWINE_PASSWORD=${PIP_TOKEN} TWINE_USERNAME=__token__ python3 -m twine upload dist/*
