stages:
  - build
  - push_image

build_devel:
  stage: build
  only:
    - devel
  script:
    - sudo docker build --no-cache -t noia/agent:latest .

build_prod:
  stage: build
  only:
    - master
  script:
    - sudo docker build --no-cache -t noia/agent:prod .

push_image_devel:
  stage: push_image
  only:
    - devel
  script:
    - sudo docker push noia/agent:latest

push_image_prod:
  stage: push_image
  only:
    - master
  script:
    - sudo docker push noia/agent:prod