variables:
  BRANCH_STABLE: "0.1"

.rules-def:
  rules:
    - if: &is-for-sandbox '$CI_COMMIT_BRANCH == "master"'
    - if: &is-for-prod '$CI_COMMIT_BRANCH == $BRANCH_STABLE'
    - if: &is-for-devel '$CI_COMMIT_TAG =~ /-(?:beta|rc)\d+$/'

stages:
  - build
  - push_image

build_sandbox:
  stage: build
  rules:
    - if: *is-for-sandbox
  script:
    - sudo docker build --no-cache -t noia/agent:sandbox-$CI_COMMIT_SHORT_SHA -t noia/agent:sandbox -t noia/agent:latest .

build_devel:
  stage: build
  rules:
    - if: *is-for-devel
  script:
    - sudo docker build --no-cache -t noia/agent:$CI_COMMIT_TAG .

build_prod:
  stage: build
  rules:
    - if: *is-for-prod
  script:
    - sudo docker build --no-cache -t noia/agent:$BRANCH_STABLE .

push_image_sandbox:
  stage: push_image
  rules:
    - if: *is-for-sandbox
  script:
    - sudo docker push noia/agent:sandbox-$CI_COMMIT_SHORT_SHA
    - sudo docker push noia/agent:sandbox
    - sudo docker push noia/agent:latest

push_image_devel:
  stage: push_image
  rules:
    - if: *is-for-devel
  script:
    - sudo docker push noia/agent:$CI_COMMIT_TAG

push_image_prod:
  stage: push_image
  rules:
    - if: *is-for-prod
  script:
    - sudo docker push noia/agent:$BRANCH_STABLE