version: '2'

services:
  portainer:
    image: portainer/agent
    restart: always
    networks:
      - syntropy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
networks:
    syntropy:
        ipam:
            config:
                - subnet: 192.168.150.0/24
