name: Azure EU gateway

connection:
  api_key: vAVlRtYoiA2rfa3NHM7mgGpN23Sg1WWH
  controller_url: controller-prod-platform-agents.noia.network
  network_api: docker
  #Select one of providers from the list or default will be assigned
  #'AWS', 'DigtialOcean', 'Microsoft Azure', 'Rackspace', 'Alibaba Cloud',
  #'Google Cloud Platform', 'Oracle Cloud', 'VMware', 'IBM Cloud', 'Vultr'.
  provider: Microsoft Azure
  #Select one of the categories from the list or default will be assigned
  # 'zIoT', 'Server','none'
  category: IoT

geo_location:
  lat: 40.14
  lon: -74.21
  country: Germany
  city: Frankfurt


#Tags (Optional)
#categorize your end-points. #You can use more than one tag.  e.g. eu-group,fr-group
tags:
  - Tag1
  - Tag2

#If `network_ids` not present the Agent will not automatically join any network when deployed
network_ids:
  - network_1
  - network_2

allowed_ips:
  - name: my_vpc
    subnet: 192.168.9.0/24
  - name: other_vpc
    subnet: 10.88.0.0/16